#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

grep -q 'gpu_backend::aevum' "$ROOT/src/marin/gpu.cpp"
grep -q 'gpu_backend::auto_select' "$ROOT/src/marin/gpu.cpp"
grep -q 'create_aevum_engine' "$ROOT/src/marin/gpu.cpp"
grep -q 'AEVUM_AUTO_MAX_RATIO' "$ROOT/src/aevum/AutoPolicy.cpp"
grep -q 'AEVUM_AUTO_PM1_STAGE1_MAX_RATIO' "$ROOT/src/aevum/AutoPolicy.cpp"
grep -q 'P-1 Stage 1' "$ROOT/src/aevum/AutoPolicy.cpp"
grep -q 'ECM conservative' "$ROOT/src/aevum/AutoPolicy.cpp"
grep -q 'pm1_lowmem' "$ROOT/src/aevum/AutoPolicy.cpp"
grep -q 'pm1_ultralowmem' "$ROOT/src/aevum/AutoPolicy.cpp"
grep -q 'Marin fast3-only one-register algorithm' "$ROOT/src/aevum/AutoPolicy.cpp"
grep -q 'bool aevum_auto = true' "$ROOT/include/io/CliParser.hpp"
grep -q 'force_engine_marin' "$ROOT/include/io/CliParser.hpp"
grep -q '"-engine-marin"' "$ROOT/src/io/CliParser.cpp"
grep -q 'engine::create_gpu' "$ROOT/src/modes/RunPrpOrLlMarin.cpp"
grep -q 'engine::create_gpu' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'engine::create_gpu' "$ROOT/src/modes/RunEcm.cpp"
grep -q 'engine::create_gpu' "$ROOT/src/modes/RunEcmTwistedEdwards.cpp"
grep -q 'engine::create_gpu' "$ROOT/src/modes/RunLlSafeMarin.cpp"
grep -q 'setBackendInfo' "$ROOT/src/marin/gpu.cpp"
grep -q 'backend_active' "$ROOT/src/ui/WebGuiServer.cpp"
grep -q 'Computation backend' "$ROOT/src/ui/WebGuiServer.cpp"
grep -q 'ECM2=1,2' "$ROOT/src/ui/WebGuiServer.cpp"
grep -q "'-llsafe2'" "$ROOT/src/ui/WebGuiServer.cpp"
! grep -q "'-llsafe'" "$ROOT/src/ui/WebGuiServer.cpp"
grep -q "parts.push('-b1',b1)" "$ROOT/src/ui/WebGuiServer.cpp"
grep -q 'pm1-stage1-large' "$ROOT/tests/run_aevum_auto_gpu_matrix.sh"
grep -q 'ECM Stage 1' "$ROOT/src/modes/RunEcm.cpp"
grep -q 'ECM Stage 2' "$ROOT/src/modes/RunEcmTwistedEdwards.cpp"
! grep -R -q 'AevumBridge\|aevum::run' "$ROOT/src" "$ROOT/include"
grep -q 'configured_gpu_backend_name' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'llsafe2_m_' "$ROOT/src/modes/RunLlSafeMarin.cpp"
grep -q 'checkpoint_backend' "$ROOT/src/modes/RunLlSafeMarin.cpp"
grep -q 'llunsafe_' "$ROOT/src/modes/RunPrpOrLlMarin.cpp"
! grep -q '\[Backend Marin\]' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'multiply_small' "$ROOT/third_party/aevum/src/EngineApi.cpp"
grep -q 'small_factor_scratch_' "$ROOT/third_party/aevum/src/EngineApi.cpp"
grep -q 'regAddWords(reg(index), small_factor_scratch_\[0\])' "$ROOT/third_party/aevum/src/EngineApi.cpp"
! grep -R -q 'regScale\|REGSCALE' "$ROOT/third_party/aevum/src"
grep -q 'Aevum uses the generic square plus base-3 multiply path; fast3 is disabled' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'useFast3Candidate && (nextStart == 0) && !aevum_backend' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'eng->is_equal(RCHK, RSTATE)' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'pm1_checkpoint_backend_matches' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'write_pm1_checkpoint_backend' "$ROOT/src/modes/RunPM1.cpp"
grep -q 'r2_2\[N_SZ / 8 + j\]' "$ROOT/kernels/marin.cl"
grep -q 'r2i_2\[N_SZ / 8 + j\]' "$ROOT/kernels/marin.cl"
grep -q 'r2_2\[N_SZ / 8 + j\]' "$ROOT/include/marin/ocl/kernel.h"
grep -q 'r2i_2\[N_SZ / 8 + j\]' "$ROOT/include/marin/ocl/kernel.h"
! grep -q 'const uint64_2 r = r2\[N_SZ / 8 + j\]' "$ROOT/kernels/marin.cl"
! grep -q 'sqr_4(xl, r2\[N_SZ / 8 + j\], r2i\[N_SZ / 8 + j\])' "$ROOT/kernels/marin.cl"
! grep -q 'mul_4(xl, yl, r2\[N_SZ / 8 + j\], r2i\[N_SZ / 8 + j\])' "$ROOT/kernels/marin.cl"
grep -q 'run_backend_validation_matrix.sh' "$ROOT/Makefile"
grep -q 'PRMERS_MATRIX_CASE_FILTER' "$ROOT/tests/run_backend_validation_matrix.sh"
grep -q 'pm1-ultralow-aevum-reject' "$ROOT/tests/run_backend_validation_matrix.sh"
grep -q 'AEVUM_VERSION ?= v0.3.4' "$ROOT/third_party/aevum/Makefile"
grep -q -- "--match 'v0.*'" "$ROOT/third_party/aevum/Makefile"
grep -q '294cc485ac8cf53c8b69144a3039832eda573849' "$ROOT/third_party/aevum/UPSTREAM.md"
grep -q '#include <filesystem>' "$ROOT/third_party/aevum/src/common.h"
! grep -q 'namespace std::filesystem' "$ROOT/third_party/aevum/src/common.h"
grep -q 'ENGINE_LINK_FLAGS = -dynamiclib' "$ROOT/third_party/aevum/Makefile"
grep -q 'DL_LIBS =' "$ROOT/third_party/aevum/Makefile"
grep -q '_NSGetExecutablePath' "$ROOT/src/aevum/EngineAevum.cpp"
grep -q 'LoadLibraryW' "$ROOT/src/aevum/EngineAevum.cpp"
grep -q 'Aevum engine plugin unavailable' "$ROOT/src/aevum/EngineAevum.cpp"
grep -q 'third_party/aevum/build-engine/libaevum_engine.so' "$ROOT/.github/workflows/build_mac_os.yml"
grep -q 'third_party/aevum/build-engine/libaevum_engine.so' "$ROOT/.github/workflows/build_linux.yml"
echo 'Aevum engine routing, auto policy, GUI and safe factor audit passed'

grep -q 'Forced Aevum request cannot be satisfied' "$ROOT/src/marin/gpu.cpp"
grep -q 'validateCompatibilityBeforeApp' "$ROOT/src/main.cpp"
grep -q -- '-llunsafe cannot use the legacy internal' "$ROOT/src/main.cpp"
grep -q -- '-pm1-ultralowmem is a Marin fast3-only' "$ROOT/src/main.cpp"
