// DoubleCheck= worktodo lines must set WorktodoEntry::doubleCheck in every form,
// including the k,b,n,c form the web GUI generates (DoubleCheck=1,2,n,-1).
// App maps doubleCheck on an LL entry to the checked LL-SAFE path and a plain
// Test= entry to the unchecked LL path, so losing the flag silently changes
// which Lucas-Lehmer implementation runs.

#include "io/WorktodoParser.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <string>

namespace {

int failures = 0;

std::optional<io::WorktodoEntry> parseLine(const std::string& line) {
    const auto path = std::filesystem::temp_directory_path() / "prmers_doublecheck_test.txt";
    {
        std::ofstream out(path);
        out << line << "\n";
    }
    io::WorktodoParser parser(path.string());
    auto entry = parser.parse();
    std::error_code ec;
    std::filesystem::remove(path, ec);
    return entry;
}

void expectLl(const std::string& line, bool doubleCheck) {
    const auto entry = parseLine(line);
    if (!entry || !entry->llTest || entry->prpTest || entry->exponent != 127U ||
        entry->doubleCheck != doubleCheck) {
        std::cerr << "FAIL " << line << ": ";
        if (!entry) std::cerr << "no entry\n";
        else std::cerr << "llTest=" << entry->llTest << " prpTest=" << entry->prpTest
                       << " exponent=" << entry->exponent
                       << " doubleCheck=" << entry->doubleCheck
                       << " (expected doubleCheck=" << doubleCheck << ")\n";
        ++failures;
    } else {
        std::cout << "PASS " << line << " -> doubleCheck=" << entry->doubleCheck << "\n";
    }
}

void expectPrp(const std::string& line) {
    const auto entry = parseLine(line);
    if (!entry || !entry->prpTest || entry->llTest || entry->doubleCheck) {
        std::cerr << "FAIL " << line << ": expected a PRP entry without doubleCheck\n";
        ++failures;
    } else {
        std::cout << "PASS " << line << " -> PRP, doubleCheck=0\n";
    }
}

} // namespace

int main() {
    const std::string aid = "0123456789ABCDEF0123456789ABCDEF";

    // k,b,n,c form (generated by the web GUI).
    expectLl("DoubleCheck=1,2,127,-1", true);
    expectLl("doublecheck=1,2,127,-1", true);
    expectLl("DoubleCheck=" + aid + ",1,2,127,-1", true);
    expectLl("DoubleCheck=N/A,1,2,127,-1", true);
    expectLl("Test=1,2,127,-1", false);
    expectLl("Test=" + aid + ",1,2,127,-1", false);

    // Prime95 form (already handled by a separate branch of the parser).
    expectLl("DoubleCheck=127,70,1", true);
    expectLl("DoubleCheck=" + aid + ",127,70,1", true);
    expectLl("Test=127,70,1", false);

    // PRP lines never carry the flag.
    expectPrp("PRP=1,2,127,-1");
    expectPrp("PRPDC=1,2,127,-1");

    if (failures != 0) {
        std::cerr << failures << " worktodo DoubleCheck check(s) failed\n";
        return 1;
    }
    std::cout << "Worktodo DoubleCheck test passed\n";
    return 0;
}
